version: "2.1"
services:
  app:
    image: app
    container_name: app
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always
    networks:
      - lab_default
    env_file:
      - ./var.env


  mysql:
    image: mysql:5.6
    restart: always
    healthcheck:
      test: "/usr/bin/mysql --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 1s
      retries: 20
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - lab_default
    env_file:
      - ./var.env
    
volumes:
  db:

  
networks:
  lab_default:
    name: lab_default
    # Use a custom driver
    driver: bridge
