services:
  app:
    build: ./app
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    restart: always


  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 1s
      retries: 20
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    
volumes:
  db:

  
