version: "2.1"
services:
  app:
    image: app
    container_name: app
    ports:
      - "8083:8083"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - lab_default


  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 1s
      timeout: 1s
      retries: 20
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - lab_default
    
volumes:
  db:

  
networks:
  lab_default:
    # Use a custom driver
    driver: bridge